language: ruby
rvm:
- 2.5.5
before_install:
- docker pull lambci/lambda:build-ruby2.5
- docker pull hashicorp/terraform:latest
- gem install bundler -v 2.0.2
install:
- bundle install
script:
- bundle exec rum plan
deploy:
- provider: script
  script: bundle exec rum apply
  skip_cleanup: true
  on:
    repo: brutalismbot/brutalismbot
    tags: true
