language: ruby
ruby:
- '2.5'
services:
- docker
install:
- make init
jobs:
  include:
    - stage: plan
      script: make plan
      if: tag IS blank
    - stage: apply
      script: make apply release=${TRAVIS_TAG}
      if: tag IS present
