language: ruby
rvm:
- 2.5.3
install:
- make init
script:
- make plan
before_deploy:
- make pkg
after_deploy:
- make apply
deploy:
- provider: s3
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  bucket: brutalismbot
  local-dir: pkg
  upload-dir: terraform/pkg
  acl: private
  skip_cleanup: true
  on:
    repo: brutalismbot/brutalismbot
    tags: true
