language: ruby
rvm:
- '2.5'
services:
- docker
before_install:
- git describe --tags --always
install:
- make init
jobs:
  include:
    - stage: plan
      script: make plan
      if: tag IS blank
    - stage: apply
      script: make plan apply release=${TRAVIS_TAG}
      if: tag IS present
