language: ruby
rvm:
- 2.5.5
install:
- docker pull lambci/lambda:build-ruby2.5
- docker pull lambci/lambda:ruby2.5
script:
- make plan
after_success:
- make test
deploy:
- provider: script
  script: make apply
  skip_cleanup: true
  on:
    repo: brutalismbot/brutalismbot
    tags: true
