version: '3'
services:

  # Base config
  base: &base
    image: lambci/lambda:ruby2.5
    env_file: .env
    volumes:
      - ./lib:/var/task

  # Cache OAuth event
  oauth:
    <<: *base
    command: oauth.handler '{"Records":[{"Sns":{"Message":"{\"ok\":true,\"access_token\":\"<token>\",\"scope\":\"identify,incoming-webhook\",\"user_id\":\"<user>\",\"team_name\":\"<team>\",\"team_id\":\"T12345678\",\"incoming_webhook\":{\"channel\":\"#brutalism\",\"channel_id\":\"C12345678\",\"configuration_url\":\"https://team.slack.com/services/B12345678\",\"url\":\"https://hooks.slack.com/services/T12345678/B12345678/123456781234567812345678\"},\"scopes\":[\"identify\",\"incoming-webhook\"]}"}}]}'

  # Cache /r/brutalism posts
  posts:
    <<: *base
    command: posts.handler '{}'

  # Dispatch /r/brutalism posts
  dispatch:
    <<: *base
    command: dispatch.handler '{"Records":[{"s3":{"bucket":{"name":"brutalismbot"},"object":{"key":"posts/v1/year%3D2019/month%3D2019-03/day%3D2019-03-26/1553565987.json"}}}]}'

  # Mirror /r/brutalism posts
  mirror:
    <<: *base
    command: mirror.handler '{"Records":[{"Sns":{"Message":"{\"bucket\":\"brutalismbot\",\"key\":\"oauth/v1/team=TGS1W4MST/channel=CGQCC0NEM/oauth.json\",\"body\":{\"blocks\":[{\"type\":\"image\",\"title\":{\"type\":\"plain_text\",\"text\":\"/r/brutalism\",\"emoji\":true},\"image_url\":\"https://i.redd.it/x11cl687uco21.jpg\",\"alt_text\":\"No. 1 Croydon - AKA Tuckersoft office.\"},{\"type\":\"context\",\"elements\":[{\"type\":\"mrkdwn\",\"text\":\"<https://reddit.com/r/brutalism/comments/b5ik43/no_1_croydon_aka_tuckersoft_office/|No. 1 Croydon - AKA Tuckersoft office.>\"}]}]}}"}}]}'

  # Uninstall app
  uninstall:
    <<: *base
    command: uninstall.handler '{"Records":[{"Sns":{"Message":"{\"token\":\"<token>\",\"team_id\":\"T1234568\",\"api_app_id\":\"A12345678\",\"event\":{\"type\":\"app_uninstalled\"},\"type\":\"event_callback\",\"event_id\":\"Ev12345678\",\"event_time\":1553557314}"}}]}'
