version: '3'
services:

  # Base config
  base: &base
    environment: &env
      AWS_ACCESS_KEY_ID:
      AWS_DEFAULT_REGION:
      AWS_SECRET_ACCESS_KEY:
      DRYRUN:
      MIN_TIME:
      S3_BUCKET:
    image: lambci/lambda:ruby2.5
    volumes:
      - ./lib:/var/task

  # Cache OAuth event
  install:
    <<: *base
    command: handlers.install '{"Records":[{"Sns":{"Message":"{\"ok\":true,\"access_token\":\"<token>\",\"scope\":\"identify,incoming-webhook\",\"user_id\":\"<user>\",\"team_name\":\"<team>\",\"team_id\":\"T12345678\",\"incoming_webhook\":{\"channel\":\"#brutalism\",\"channel_id\":\"C12345678\",\"configuration_url\":\"https://team.slack.com/services/B12345678\",\"url\":\"https://hooks.slack.com/services/T12345678/B12345678/123456781234567812345678\"},\"scopes\":[\"identify\",\"incoming-webhook\"]}"}}]}'

  # Cache /r/brutalism posts
  cache:
    <<: *base
    command: handlers.cache

  # Mirror /r/brutalism posts
  mirror:
    <<: *base
    command: handlers.mirror '{"Records":[{"s3":{"bucket":{"name":"brutalismbot"},"object":{"key":"posts/v1/year%3D2019/month%3D2019-04/day%3D2019-04-20/1555799559.json"}}}]}'

  # Uninstall app
  uninstall:
    <<: *base
    command: handlers.uninstall '{"Records":[{"Sns":{"Message":"{\"token\":\"<token>\",\"team_id\":\"T1234568\",\"api_app_id\":\"A12345678\",\"event\":{\"type\":\"app_uninstalled\"},\"type\":\"event_callback\",\"event_id\":\"Ev12345678\",\"event_time\":1553557314}"}}]}'

  # Deployment
  terraform:
    <<: *base
    environment:
      <<: *env
      TF_VAR_slack_client_id:
      TF_VAR_slack_client_secret:
      TF_VAR_slack_oauth_error_uri:
      TF_VAR_slack_oauth_redirect_uri:
      TF_VAR_slack_oauth_success_uri:
      TF_VAR_slack_signing_secret:
      TF_VAR_slack_signing_version:
      TF_VAR_slack_token:
    image: hashicorp/terraform
    volumes:
      - ./:/var/task
      - terraform:/var/task/.terraform
    working_dir: /var/task

volumes:
  terraform:
