version: '3'
services:

  # Base config
  base: &base
    image: lambci/lambda:ruby2.5
    env_file: .env
    volumes:
      - ./lib:/var/task

  # Cache OAuth event
  install:
    <<: *base
    command: handlers.install '{"Records":[{"Sns":{"Message":"{\"ok\":true,\"access_token\":\"<token>\",\"scope\":\"identify,incoming-webhook\",\"user_id\":\"<user>\",\"team_name\":\"<team>\",\"team_id\":\"T12345678\",\"incoming_webhook\":{\"channel\":\"#brutalism\",\"channel_id\":\"C12345678\",\"configuration_url\":\"https://team.slack.com/services/B12345678\",\"url\":\"https://hooks.slack.com/services/T12345678/B12345678/123456781234567812345678\"},\"scopes\":[\"identify\",\"incoming-webhook\"]}"}}]}'

  # Cache /r/brutalism posts
  cache:
    <<: *base
    environment:
      MIN_TIME:
    command: handlers.cache

  # Mirror /r/brutalism posts
  mirror:
    <<: *base
    command: handlers.mirror '{"Records":[{"s3":{"bucket":{"name":"brutalismbot"},"object":{"key":"posts/v1/year%3D2019/month%3D2019-03/day%3D2019-03-26/1553565987.json"}}}]}'

  # Uninstall app
  uninstall:
    <<: *base
    command: handlers.uninstall '{"Records":[{"Sns":{"Message":"{\"token\":\"<token>\",\"team_id\":\"T1234568\",\"api_app_id\":\"A12345678\",\"event\":{\"type\":\"app_uninstalled\"},\"type\":\"event_callback\",\"event_id\":\"Ev12345678\",\"event_time\":1553557314}"}}]}'
