name: plan

on:
  pull_request:
  push:
    branches:
    - master
  schedule:
  - cron: "11 21 * * *"

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
    - name: setup
      run: |
        gem install bundler -v 2.1.2
        bundle install --jobs 4 --retry 3
        docker pull lambci/lambda:build-ruby2.5
        docker pull lambci/lambda:ruby2.5
        docker pull hashicorp/terraform
    - name: plan
      run: bundle exec rum plan
